name: ShiftEnchant
version: 1.1.0-ALPHA-SNAPSHOT
main: com.gmail.gogobebe2.shiftenchant.ShiftEnchant
description: implements a gui that pops up to enchant items.
author: William Bryant (gogobebe2)
website: gogobebe2@gmail.com
commands:
  ench:
    aliases: [enchant]